//Exercise #1

When a Mule app starts, a connectivity test runs on thecomponentss, such as the HTTP or FTP connector, that needs to be connected to an external server, and if the test fails, the default behaviour is supposed to be logged with a warning message and continue with the deployment of the app instead of blocking the deployment.

You can modify this behaviour by setting a number of reconnections attempt to try after an initial failure and by forcing the deployment to fail when all connections attempt to fail.

* **Fail Deployment (`failsDeployment`):** Forces the deployment to fail if the connection fails and any configured reconection attempts is exhausted.
* **Reconnect (`reconnect`):** Limits the number of reconnections attempt and the interval at which to execute them. For example, you might set a count of 5 reconnections attempt at a `frequency` of every `4000` milliseconds (ms). Default is to 2 reconnections attempt at a frequency of `2000ms`.
* Example with those fails after 5 reconnections, attempts are exhausted:

[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-conection host="https://jsonplaceholder.typicode.com/posts" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000" count="5" />
    </reconnection
  </http:request-connection>
</http:request-config>
----

* **Reconnect Forever (reconnect-forever):** Attempts to reconnect at a given interval, for example, every 4000 ms for as long as the app runs. Default is to every 2000 ms because there is no limit on the number of retries and no value for count is specified.

* Example that does not set a limit on the number of reconnections attempt:

[source,xml]
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
  <reconnection>
    <reconnect-forever frequency="4000" count=”5”/>
  </reconnection>
</http:request-connectio>
----
